var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dim",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fév",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Juin",
            "jul": "Jui",
            "aug": "Août",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Déc"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Cliquez pour voir la date d'aujourd'hui",
        "i_undefined": "Indéfini",
        "allday_event": "Événement toute la journée",
        "repeat_event": "Événement répété",
        "time": "Temps",
        "event": "Événement",
        "location": "Endroit",
        "participant": "Participant",
        "get_data_exception": "Exception lors du téléchargement de données",
        "new_event": "Nouvel événement",
        "confirm_delete_event": "Voulez-vous vraiment supprimer cet événement? ",
        "confrim_delete_event_or_all": "Voulez-vous aussi supprimer les événements répétés? \r\nCliquez [OK] pour ne supprimer que cet événement, cliquez [Cancel] pour supprimer tous les événements",
        "data_format_error": "Erreur de format",
        "invalid_title": "Le titre ne peux pas être vide or contenir ($<>)",
        "view_no_ready": "View is not ready",
        "example": "ex: Français Groupe 3",
        "content": "Quoi?",
        "create_event": "Créer événement",
        "update_detail": "Éditer les details",
        "click_to_detail": "Voir détails",
        "i_delete": "Supprimer",
        "day_plural": "jours",
        "others": "Autres",
        "item": ""
    }
});
