timetable_event:
    pattern:  /
    defaults: { _controller: "PlaniwebModelBundle:TimetableEvent:index" }

timetable_event_show:
    pattern:  /{id}/show
    defaults: { _controller: "PlaniwebModelBundle:TimetableEvent:show" }


timetable_event_create:
    pattern:  /create
    defaults: { _controller: "PlaniwebModelBundle:TimetableEvent:create" }
    requirements: { _method: post }


timetable_event_update:
    pattern:  /{id}/update
    defaults: { _controller: "PlaniwebModelBundle:TimetableEvent:update" }
    requirements: { _method: post|put }

timetable_event_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PlaniwebModelBundle:TimetableEvent:delete" }
    requirements: { _method: post|delete }
