timetable_event_instance_activity:
    pattern:  /
    defaults: { _controller: "PlaniwebModelBundle:TimetableEventInstanceActivity:index" }

timetable_event_instance_activity_show:
    pattern:  /{id}/show
    defaults: { _controller: "PlaniwebModelBundle:TimetableEventInstanceActivity:show" }


timetable_event_instance_activity_create:
    pattern:  /create
    defaults: { _controller: "PlaniwebModelBundle:TimetableEventInstanceActivity:create" }
    requirements: { _method: post }


timetable_event_instance_activity_update:
    pattern:  /{id}/update
    defaults: { _controller: "PlaniwebModelBundle:TimetableEventInstanceActivity:update" }
    requirements: { _method: post|put }

timetable_event_instance_activity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PlaniwebModelBundle:TimetableEventInstanceActivity:delete" }
    requirements: { _method: post|delete }
