user_comment:
    pattern:  /
    defaults: { _controller: "PlaniwebModelBundle:UserComment:index" }

user_comment_show:
    pattern:  /{id}/show
    defaults: { _controller: "PlaniwebModelBundle:UserComment:show" }


user_comment_create:
    pattern:  /create
    defaults: { _controller: "PlaniwebModelBundle:UserComment:create" }
    requirements: { _method: post }


user_comment_update:
    pattern:  /{id}/update
    defaults: { _controller: "PlaniwebModelBundle:UserComment:update" }
    requirements: { _method: post|put }

user_comment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PlaniwebModelBundle:UserComment:delete" }
    requirements: { _method: post|delete }
