PlaniwebModelbundle_user:
    resource: "@PlaniwebModelBundle/Resources/config/routing/user.yml"
    prefix: /user

PlaniwebModelBundle_student:
    resource: "@PlaniwebModelBundle/Resources/config/routing/student.yml"
    prefix:   /student

PlaniwebModelBundle_ctudent:
    resource: "@PlaniwebModelBundle/Resources/config/routing/course.yml"
    prefix:   /course

PlaniwebModelBundle_course_activity:
    resource: "@PlaniwebModelBundle/Resources/config/routing/courseactivity.yml"
    prefix:   /course_activity

PlaniwebModelBundle_timetable_event:
    resource: "@PlaniwebModelBundle/Resources/config/routing/timetableevent.yml"
    prefix:   /timetable_event

PlaniwebModelBundle_timetable_event_activity:
    resource: "@PlaniwebModelBundle/Resources/config/routing/timetableeventactivity.yml"
    prefix:   /timetable_event_activity

PlaniwebModelBundle_timetable_event_instance:
    resource: "@PlaniwebModelBundle/Resources/config/routing/timetableeventinstance.yml"
    prefix:   /timetable_event_instance

PlaniwebModelBundle_timetable_event_instance_activity:
    resource: "@PlaniwebModelBundle/Resources/config/routing/timetableeventinstanceactivity.yml"
    prefix:   /timetable_event_instance_activity

PlaniwebModelBundle_user_comment:
    resource: "@PlaniwebModelBundle/Resources/config/routing/usercomment.yml"
    prefix:   /user_comment

PlaniwebModelBundle_user_comment_context:
    resource: "@PlaniwebModelBundle/Resources/config/routing/usercommentcontext.yml"
    prefix:   /user_comment_context