<?php

namespace Planiweb\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TimetableEventInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetableEventInstanceRepository extends EntityRepository
{
}
