<?php

namespace Planiweb\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCommentRepository extends EntityRepository
{
}
